import httpx

from switchgear.auth import hash_password, verify_session
from switchgear.config import Settings
from switchgear.storage.memory import MemoryStorage
from switchgear.web.app import create_app
from switchgear.web.setup_routes import (
    ensure_session_secret,
    ensure_setup_token,
    is_claimed,
)
from tests.fakes import FakeGateway


def make_unclaimed_app(storage=None, **overrides):
    settings = Settings(_env_file=None, **overrides)
    return create_app(settings=settings, storage=storage or MemoryStorage(),
                      gateway=FakeGateway([]))


def client(app):
    return httpx.AsyncClient(transport=httpx.ASGITransport(app=app),
                             base_url="http://t")


async def test_status_reports_unclaimed_then_claimed():
    app = make_unclaimed_app()
    async with client(app) as c:
        assert (await c.get("/api/setup/status")).json() == {"claimed": False}
    app.state.switchgear.settings.local_password_hash = "scrypt:x"
    async with client(app) as c:
        assert (await c.get("/api/setup/status")).json() == {"claimed": True}


async def test_setup_token_persists_and_env_wins():
    storage = MemoryStorage()
    app = make_unclaimed_app(storage)
    state = app.state.switchgear
    token1 = await ensure_setup_token(state)
    token2 = await ensure_setup_token(state)
    assert token1 == token2 and len(token1) >= 24
    assert (await storage.get("app-settings", "setup-token"))["token"] == token1

    preset = make_unclaimed_app(setup_token="preset-tok")
    assert await ensure_setup_token(preset.state.switchgear) == "preset-tok"


async def test_claim_happy_path_sets_cookie_and_deletes_token():
    storage = MemoryStorage()
    app = make_unclaimed_app(storage)
    state = app.state.switchgear
    token = await ensure_setup_token(state)
    async with client(app) as c:
        response = await c.post("/api/setup/claim", json={
            "token": token, "password": "hunter22-long",
            "owner_email": "me@example.com", "owner_timezone": "America/New_York"})
    assert response.status_code == 200
    assert is_claimed(state.settings)
    assert state.settings.owner_email == "me@example.com"
    assert state.settings.owner_timezone == "America/New_York"
    assert verify_session(state.settings, response.cookies.get("session")) \
        == "me@example.com"
    assert await storage.get("app-settings", "setup-token") is None
    secure = await storage.get("app-settings", "secure")
    assert secure["owner_email"] == "me@example.com"
    assert (await storage.get("app-settings", "user"))["owner_timezone"] \
        == "America/New_York"


async def test_claim_rejects_bad_token_and_short_password(monkeypatch):
    import asyncio as aio

    async def no_sleep(_):
        pass

    monkeypatch.setattr(aio, "sleep", no_sleep)
    app = make_unclaimed_app()
    token = await ensure_setup_token(app.state.switchgear)
    async with client(app) as c:
        bad = await c.post("/api/setup/claim", json={
            "token": "wrong", "password": "hunter22-long",
            "owner_email": "me@example.com"})
        assert bad.status_code == 403
        short = await c.post("/api/setup/claim", json={
            "token": token, "password": "short", "owner_email": "me@example.com"})
        assert short.status_code == 422


async def test_claim_conflicts_when_already_claimed():
    app = make_unclaimed_app(local_password_hash=hash_password("existing-pass"),
                             owner_email="own@x.y")
    async with client(app) as c:
        response = await c.post("/api/setup/claim", json={
            "token": "any", "password": "hunter22-long",
            "owner_email": "me@example.com"})
    assert response.status_code == 409


async def test_session_secret_autogenerated_and_stable():
    storage = MemoryStorage()
    app = make_unclaimed_app(storage)
    await ensure_session_secret(app.state.switchgear)
    first = app.state.switchgear.settings.session_secret
    assert first != "dev-secret-change-me" and len(first) == 64

    app2 = make_unclaimed_app(storage)
    await ensure_session_secret(app2.state.switchgear)
    assert app2.state.switchgear.settings.session_secret == first

    explicit = make_unclaimed_app(MemoryStorage(), session_secret="explicit")
    await ensure_session_secret(explicit.state.switchgear)
    assert explicit.state.switchgear.settings.session_secret == "explicit"


async def test_unclaimed_login_redirects_to_setup():
    app = make_unclaimed_app()
    async with client(app) as c:
        response = await c.get("/login")
    assert response.status_code == 307
    assert response.headers["location"] == "/setup"


async def test_setup_page_redirects_home_when_claimed():
    app = make_unclaimed_app(local_password_hash="scrypt:x", owner_email="o@x.y")
    async with client(app) as c:
        response = await c.get("/setup")
    assert response.status_code == 307
    assert response.headers["location"] == "/"
